name: Testing workflow
on:
  push:
    branches: 
      - master
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.actor }}"
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 21
        cache: maven
    - name: Change the directory
    - run: cd FirstProject
    - name: Listing out directory files
    - run: ls -a
    - name: Build with Maven
    - run: mvn -B package --file pom.xml
    
