name: Testing workflow
on:
  push:
    branches: 
      - master
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.actor }}"
  MavenBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
        cache: maven
    - name: Change the directory and Build with Maven
      run: | 
        cd FirstProject
        ls -a
        mvn clean install -DskipTests
        mvn -B package --file pom.xml 
  MavenRunScript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
        cache: maven
    - name: Change the directory and Build with Maven
      run: | 
        cd FirstProject
        ls -a
        mvn clean install
  UploadingArtifacts:
    runs-on: ubuntu-latest
    steps:
    - name: Uploading the artifacts
      uses: actions/upload-artifact@v4
      with:
        name: 'Artifacts for future ref'
        path: './FirstProject/*'
